[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
compliant_registry = "hhcx645NBLLRrKry3dkDMTMzZfrCUEJk3UurUYBxjww"
transfer_hook = "4CoN4C1mqdkgvgQeXMSa1Pnb7guFH89DekEvRHgKmivf"

[programs.localnet]
compliant_registry = "66tKcQqpv8GH2igWWBcLVrTjvo8cgpVJJAE8xadAgnYA"
transfer_hook = "5DLH2UrDD5bJFadn1gV1rof6sJ7MzJbVNnUfVMtGJgSL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
